baseURL: "https://kranurag7.github.io/blog"
title: kranurag7 blog 
paginate: 5
theme: hugo-PaperMod


params:
    homeInfoParams:
        Title: Hi there ğŸ‘‹ğŸ»
        Content: Welcome to my blog


    socialIcons: 
        - name: "github"
          url: "https://github.com/kranurag7"
        - name: "twitter"
          url: "https://twitter.com/KrAnurag7"


  